services:
  ebanx-api:
    image: liveorder-api:latest
    build:
      context: .
      dockerfile: Luciano.Serafim.Ebanx.Account.Api/Dockerfile
      args:
        - configuration=Debug
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    depends_on:
      - mongodb
      - redis
  redis:
    image: redis/redis-stack-server:latest
    ports: 
      - "6379:6379"
  mongodb:
    image: mongodb/mongodb-community-server:latest
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 27017:27017
    volumes:
      - './.data:/data/db'  
    command: --replSet rs0 --bind_ip 0.0.0.0
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongodb:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30    
  mongo-express:
    image: mongo-express:latest
    ports: 
      - 8085:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb      
      ME_CONFIG_BASICAUTH_USERNAME: mongo
      ME_CONFIG_BASICAUTH_PASSWORD: mongo 
